apiVersion: apps/v1
kind: Deployment
metadata:
  name: gs
  labels:
    app: ggyo
    component: gs
spec:
  selector:
    matchLabels:
      app: ggyo
      component: gs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ggyo
        component: gs
    spec:
      containers:
      - name: gs
        image: gcr.io/ggyo-281409/ggyo:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_PASS
          value: password
          env:
        - name: MAIL_NAME
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: name
        - name: MAIL_EMAIL
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: email
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: password
        ports:
        - containerPort: 8383
