apiVersion: v1
kind: Service
metadata:
  name: gs
spec:
  ports:
  - port: 8383
  selector:
    app: gs
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: gs
spec:
  selector:
    matchLabels:
      app: gs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gs
    spec:
      containers:
      - name: gs
        image: gcr.io/ggyo-281409/ggyo
        imagePullPolicy: Never
        env:
        - name: DB_PASS
          value: password
          env:
        - name: MAIL_NAME
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: name
        - name: MAIL_EMAIL
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: email
        - name: MAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mail-secret
              key: password
        ports:
        - containerPort: 8383
          
