name: buildah

on: [push, pull_request]

jobs:
  buildah:
    runs-on: ubuntu-22.04
    env:
      IMAGE: ggyo
      TAG: ${{ github.sha }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: enable emulation to support any non-native RUN instructions
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qemu binfmt-support qemu-user-static \
            podman buildah skopeo
          sudo update-binfmts --display

      - name: build images
        run: |
          podman version
          buildah version
          buildah build \
            --jobs=4 \
            --build-arg tag=$TAG \
            --platform=linux/amd64,linux/arm64 \
            --manifest $IMAGE:$TAG

          skopeo inspect --raw containers-storage:localhost/$IMAGE:$TAG
          buildah images

      - name: configure gcloud
        env:
           GCP_EMAIL: ${{ secrets.GCP_EMAIL }}
           GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
           GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
           GCP_CLUSTER: ${{ secrets.GCP_CLUSTER }}
           GCP_ZONE: ${{ secrets.GCP_ZONE }}
        run: |
          gcf=$(mktemp)
          echo "$GCP_CREDENTIALS" > $gcf
          gcloud auth activate-service-account $GCP_EMAIL --key-file=$gcf --project=$GCP_PROJECT
          gcloud info
          gcloud auth configure-docker
          gcloud container clusters get-credentials $GCP_CLUSTER -z $GCP_ZONE

      - name: publish image
        env:
           GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        run: |
          GKE_IMAGE=gcr.io/$GCP_PROJECT/$IMAGE

          echo "ℹ️ Tagging $GKE_IMAGE:$TAG"
          buildah tag localhost/$IMAGE:$TAG $GKE_IMAGE:$TAG
          echo "ℹ️ Inspect $GKE_IMAGE:$TAG"
          skopeo inspect --raw containers-storage:localhost/$IMAGE:$TAG
          echo "ℹ️ Push manifest and images $GKE_IMAGE:$TAG"
          podman manifest push --all $GKE_IMAGE:$TAG docker://$GKE_IMAGE:$TAG
          echo "ℹ️ Inspect $GKE_IMAGE:$TAG"
          skopeo inspect --raw docker://$GKE_IMAGE:$TAG
          echo "ℹ️ Tagging $GKE_IMAGE:latest"
          buildah tag localhost/$IMAGE:$TAG $GKE_IMAGE:latest
          echo "ℹ️ Push manifest and images $GKE_IMAGE:latest"
          podman manifest push --all $GKE_IMAGE:latest docker://$GKE_IMAGE:latest
          echo "ℹ️ Inspect $GKE_IMAGE:latest"
          skopeo inspect --raw docker://$GKE_IMAGE:latest

      - name: deploy
        env:
           MAIL_SECRET: ${{ secrets.MAIL_SECRET }}
        run: |
          echo "$MAIL_SECRET" > ./k8s/mail-secret.yaml
          sed -i -e 's/imagePullPolicy:.*$/imagePullPolicy: Always/' k8s/gs-deployment.yaml
          make redeploy
